-- public.laporan_kegiatan definition

-- Drop table

DROP TABLE public.laporan_kegiatan;

CREATE TABLE public.laporan_kegiatan (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	is_deleted int4 NULL DEFAULT 0,
	deleted_by varchar(64) NULL,
	deleted_at timestamp NULL,
	created_by varchar(64) NOT NULL,
	created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by varchar(64) NULL,
	updated_at timestamp NULL,
	id_bidang_wilayah int4 NOT NULL,
    kegiatan_id_jenis_kegiatan int4 NOT NULL,
    kegiatan_jmlh_personil SMALLINT NOT NULL,
    kegiatan_id_asal_laporan int4 NULL,
    kegiatan_id_jenis_pengamanan int4 NULL,
    kegiatan_masalah varchar(128) NULL,
    kegiatan_pemecahan_masalah varchar(128) NULL,
    kegiatan_instansi_terkait varchar(128) NULL,
    kegiatan_uraian_kegiatan varchar(128) NULL,
    tindak_lanjut_administrasi_id_jenis_pasal int4 NULL,
    tindak_lanjut_id_penyelesaian int4 NULL,
    tindak_lanjut_id_proses_khusus int4 NULL,
    tindak_lanjut_identitas_nama_usaha_no_bap varchar(64) NULL,
    tindak_lanjut_identitas_nama_usaha_nama_penanggung_jawab varchar(64) NULL,
    tindak_lanjut_identitas_nama_usaha_nama_usaha_tempat varchar(64) NULL,
    tindak_lanjut_identitas_nama_usaha_nik_paspor varchar(64) NULL,
    tindak_lanjut_identitas_nama_usaha_alamat varchar(255) NULL,
    tindak_lanjut_id_jenis_usaha_tempat int4 NULL,
    tindak_lanjut_id_penindakan int4 NULL,
    tindak_lanjut_jumlah_penindakan SMALLINT NULL,
    tindak_lanjut_jumlah_pelanggar SMALLINT NULL,
    tindak_lanjut_jumlah_denda_pengadilan DECIMAL NULL,
    tindak_lanjut_jumlah_denda_non_pengadilan DECIMAL NULL,
    tindak_lanjut_jumlah_denda_tanggal_setor DATE NULL,
    tindak_lanjut_jumlah_denda_nama_bank varchar(64) NULL,
    tindak_lanjut_jumlah_denda_no_validasi_bank varchar(64) NULL,
    tindak_lanjut_tanggal_sidang DATE NULL,
    tindak_lanjut_jumlah_pelanggar_hadir_sidang SMALLINT NULL,
    tindak_lanjut_jumlah_pelanggar_tidak_hadir SMALLINT NULL,
    tindak_lanjut_jumlah_pelanggar_verstek SMALLINT NULL,
    tindak_lanjut_rekomendasi_citata_id_jenis_pelanggaran_bangunan int4 NULL,
    tindak_lanjut_rekomendasi_citata_no_sp varchar(64) NULL,
    tindak_lanjut_rekomendasi_citata_tgl_sp DATE NULL,
    tindak_lanjut_rekomendasi_citata_no_segel varchar(64) NULL,
    tindak_lanjut_rekomendasi_citata_tgl_segel DATE NULL,
    tindak_lanjut_rekomendasi_citata_no_spb varchar(64) NULL,
    tindak_lanjut_rekomendasi_citata_tgl_spb DATE NULL,
    tindak_lanjut_rekomendasi_citata_no_rekomtek varchar(64) NULL,
    tindak_lanjut_rekomendasi_citata_tgl_rekomtek DATE NULL,
    tindak_lanjut_rekomendasi_citata_peninjau_lapangan DATE NULL,
	CONSTRAINT laporan_kegiatan_pkey PRIMARY KEY (id)
);